### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by gbtami** [lukasmonk/lucaschessR#2]
"Changed in version 3.3: On Linux, sys.platform doesn’t contain the major version anymore. It is always 'linux', instead of 'linux2' or 'linux3'. Since older Python versions include the version number, it is recommended to always use the startswith idiom presented above."
After changing platform check
```
-isLinux = sys.platform == "linux2"
+isLinux = sys.platform == "linux"
```
I get this error:
```
tamas@tami:~/lucaschessR/bin$ python3 LucasR.py 
Traceback (most recent call last):
  File "LucasR.py", line 16, in <module>
    import Code.Init
  File "/home/tamas/lucaschessR/bin/Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "/home/tamas/lucaschessR/bin/Code/Procesador.py", line 8, in <module>
    from Code import AperturasStd
  File "/home/tamas/lucaschessR/bin/Code/AperturasStd.py", line 1, in <module>
    import FasterCode
ModuleNotFoundError: No module named 'FasterCode'
```

**Comment by lukasmonk** [comment]
This is part of the Linux support, there is a folder .fastercode, it is needed to compile, to create FasterCode.
Then copy to OS/<???> folder. There are a lot of work, like to add this folder with Linux engines and code to work with.

**Comment by lukasmonk** [comment]
I have added some code to support linux 64bits, but it needs a lot of tests.

**Comment by gbtami** [comment]
Seems setup_linux.py is missing from git. Telling the truth I have 0 experience using Cython, so I just renamed setup.py. After installing latest cython from pip I got this:

```
tamas@tami:~/lucaschessR/bin/.fastercode$ ./linux64.sh 
Traceback (most recent call last):
  File "./setup_linux.py", line 3, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
```

I read this interesting post today. http://blog.behnel.de/posts/ship-generated-c-code-or-not.html
Maybe worth to consider.

**Comment by lukasmonk** [comment]
Fixed.
I will prefer include pyx files, because they can be changed or improved not the c result.

**Comment by gbtami** [comment]
I still get: ImportError: No module named Cython.Distutils
I installed Cython with pip.
```
tamas@tami:~/lucaschessR/bin/.fastercode$ pip3 list | grep Cython
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
Cython (0.29.20)
```

**Comment by lukasmonk** [comment]
This can help:
https://stackoverflow.com/questions/11108461/importerror-no-module-named-cython-distutils

**Comment by gbtami** [comment]
That helped (indirectly), thx.
I suggest to change to change in linux64.sh
from
python ./setup_linux.py build_ext --inplace --verbose
to
python3 ./setup_linux.py build_ext --inplace --verbose

You should also make linux64.sh executable in git sources also.

**Comment by gbtami** [comment]
Btw please fix platform check I suggested in my very first comment.

**Comment by lukasmonk** [comment]
linux64.sh: python -> python3
platform: linux2 -> linux

linux64.sh executable, I have no idea

**Comment by gbtami** [comment]
sudo chmod +x linux64.sh

**Comment by lukasmonk** [comment]
ok. but from git working in Windows.

**Comment by gbtami** [comment]
Progress. On Ubuntu 18.04 Python3 version is 3.6.9, so the resulting modul name is 
FasterCode.cpython-36m-x86_64-linux-gnu.so (linux64.sh copy failed)
After copying it manually to OS/linux I get
```
tamas@tami:~/lucaschessR/bin$ python3 LucasR.py 
Traceback (most recent call last):
  File "LucasR.py", line 16, in <module>
    import Code.Init
  File "/home/tamas/lucaschessR/bin/Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "/home/tamas/lucaschessR/bin/Code/Procesador.py", line 8, in <module>
    from Code import AperturasStd
  File "/home/tamas/lucaschessR/bin/Code/AperturasStd.py", line 1, in <module>
    import FasterCode
ImportError: /home/tamas/lucaschessR/bin/OS/linux/FasterCode.cpython-36m-x86_64-linux-gnu.so: undefined symbol: move_from_string
```

**Comment by lukasmonk** [comment]
You need to copy irina.so too.

**Comment by gbtami** [comment]
irina.so file name doesn't depend on Python3 version (contrary to FasterCode  .so) so copy was successful.

Above error indicates that when Python3 is trying to import FasterCode module from FasterCode.cpython-36m-x86_64-linux-gnu.so it has issues with move_from_string somehow.

**Comment by lukasmonk** [comment]
python 3.7.7
It doesn´t work to me.
Perhaps it is needed something like

#!/usr/bin/env bash

export LD_LIBRARY_PATH=$(pwd)/OS/linux
python3 ./Lucas.py

**Comment by marmistrz** [comment]
IMO detailed build instructions should be present in the README. And what in world is fastercode and why is it a hidden directory?

**Comment by lukasmonk** [comment]
My idea is to create a binary to install it in the same way as Windows. I don´t know if I'll be successful, I'll probably have to ask for help.
FasterCode, is hidden from Linux point of view, not from Windows, and this is why.
In the next version I will take this into account, I will use another prefix to differentiate it from the rest of the code.
FasterCode has some functions that I want to be faster than the Python standard. Includes c code and cython code.

**Comment by lukasmonk** [comment]
Yes, this seems like a fancy way to include some code with less relation to the rest.
I work from an identical copy of the GitHub repository, the relationship is 1: 1, this makes it easier for me to control the application, and it simplifies this part for me. Then I have a couple of scripts to generate the windows executable, and the clean code to update from github. Simplicity to the maximum, perhaps not the best but the simplest.
