### ISSUE TITLE
Wrong name in Engine folder

### ISSUE THREAD

**Issue by cescgina** [lukasmonk/lucaschessR#34]
After compiling for linux I got an error:

`RecursionError: maximum recursion depth exceeded while calling a Python object`

After poking aroung in the Code/Config/Configuration.py I realised that the problem was that the Stockfish was misspelled ("stockfish" with a lowercase s, instead of "Stockfish") which caused an infinite recursion looking for the engine. Changing the folder name in bin/OS/linux/ to "Stockfish" solved the problem for me.

**Comment by lukasmonk** [comment]
Thank you. Laudecir Daniel had fixed it and I forgot to publish it.
It is now fixed in version 1.21

**Comment by cescgina** [comment]
I'm reopening this issue since I did a new test with the latest release (1.21) and a similar issue still persists. The path in the install script is wrong, and some engines executables do not get the right permissions, and the program does not find them.

**Comment by lukasmonk** [comment]
Ok Fixed linux64.sh.

**Comment by lukasmonk** [comment]
Sorry. Changed again.
