### ISSUE TITLE
Opening Lines issues/changes

### ISSUE THREAD

**Issue by tkozybski** [lukasmonk/lucaschessR#44]
1) When I do Mass Analysis, set the time to 0 and depth to wanted value, it'll analyse to that depth or 1000 seconds. How do I setup it so it doesn't have this 1000s, or maybe it is a bug?

2) Also in mass analysis, about lines amount. Can we change the dropdown amount to a textbox like it is for seconds and in main window view? I usually want to do 2 moves, the best move and alternative, but right now it only allows 1,3,5,10, there's no in between.

3) When exporting PGN, would it be possible to add two optional settings? To include comments from the program to the pgn, and second one to also add engine analysis to the exported comment.

Cheers

**Comment by lukasmonk** [comment]
1, In theory it is fixed in version 1.25.
2. Added in version 1.25a
3. Need more information, Do you need to add or delete this data?

**Comment by tkozybski** [comment]
Thank you.

3. Add that information to exported PGN into a comment to the move. Comments & Engine analysis lines.

Also, if it's not a problem, when Importing lines from another database, comments and engine analysis is not imported with them. Would be great if they would.

**Comment by tkozybski** [comment]
@lukasmonk I've updated to 1.25a but I still see only 1/3/5 depth in opening lines mass analysis. I see you changed the WindowAnalysisParam.py but not bin/Code/Openings/WindowOpeningLine.py

**Comment by lukasmonk** [comment]
Sorry, I have only partially changed the file.

If you want, you can download, WIndowOpeningLine.pyc and replace the file in the installation.
https://drive.google.com/file/d/1WtcEkAVORpq0k7hUlod-yCd7xhcKekSM/view?usp=sharing

Also, the source:
https://drive.google.com/file/d/1-Ji_hv2B2g1ZPdekUrkhfuovkPhCUGRo/view?usp=sharing

**Comment by tkozybski** [comment]
Hello. The file you incldued is WindowAnalysisParam, not WindowOpeningLine, also, you didn't make the change in 1.26. The file you have to change is bin\Code\Openings\WindowOpeningLine

**Comment by lukasmonk** [comment]
Sorry test this:
https://drive.google.com/file/d/1A3z4n-ZpFylTlwLW0x9HATRRqaj979JO/view?usp=sharing

**Comment by tkozybski** [comment]
Looks like it works :)
